baseURL = "https://www.akiamarketing.ca/"
DefaultContentLanguage = "fr"
title = "Akia Marketing"
theme = "akia"
description = ""

# Pointing to this file
config = "config.toml"
contentdir = "content"
disableKinds = ["RSS"]
# Create an array of files you don't want hugo to build
ignoreFiles = []
# Enable Logging
log = false
preserveTaxonomyNames = true
pygmentsUseClasses = true
relativeURLs = true
languageCode = "en-us"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

#CUSTOM PARAMS
[params]
  ## Include google maps, with API Key
  googleapikey = "AIzaSyDhBhixIN3u8BHQ86aS_TD0D0W9J2w9ikg"
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://www.akiamarketing.ca/"
  siteaddressno = "https://www.akiamarketing.ca"
  ## FB share info
  fbpagename = ""
  fbappid = ""
  ## Business name in Schema.org
  schemabiz = "Akia Marketing"
  ## Google Tag Manager tracking ID
  gtmid = "GTM-P4S6BJQ"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[permalinks]
  singles = "/:slug/"

[Languages.fr]
[Languages.fr.Taxonomies]
category = "categories"
portfolio = "portfolios"
