backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
  branch: development # Branch to update (master by default)

media_folder: "themes/akia/source-images" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with

publish_mode: editorial_workflow

collections:
### ARTICLES
  - name: "articles" # Used in routes, e.g. /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    editor:
      preview: true
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "fr"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Slug/Link (if link is https://www.akiamarketing.ca/articles/tiny-house-roof, value is tiny-house-roof)", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
      - label: "Author" 
        name: "author"
        widget: "select"
        options:
          - { label: "Alexis Grenon", value: "alexis" }
          - { label: "Robin Lamoureux", value: "robin" }
          - { label: "Kamel Gorieze", value: "kamel" }
          - { label: "Félix DeBlois-Beaucage", value: "felix" }
      - {label: "Share image (1200px by 630px)", name: "image", widget: "image" , required: false}
      - {label: "Publication date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - name: listing
        label: "Home page and articles page"
        widget: object
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Summary", name: "description", widget: "text"}
      - {label: "Categories (separate with commas)", name: "categories", widget: "list", required: false}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "fr"}
      - {label: "Menu ID", name: "menuid", widget: "hidden", default: "articles"}
      - {label: "Priority (0 is the most important)", name: "ordre", widget: "number", default: 0, required: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Hide from website?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Remove from search engine?", name: "noindex", widget: "boolean", required: false, default: false}
### PAGES
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "accueil"
        label: "Accueil"
        file: "content/_index.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Hide from website?", name: "draft", widget: "boolean", required: false, default: false}
          - {label: "Remove from search engine?", name: "noindex", widget: "boolean", required: false, default: false}
          - label: "Section 1" 
            name: "section1" 
            widget: "object" 
            fields:
              - {label: "Subtitle (on top)", name: "subtitle", widget: "string"}
              - {label: "Ligne 1", name: "line1", widget: "string"}
              - {label: "Ligne 2", name: "line2", widget: "string"}
              - {label: "Ligne 3", name: "line3", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - label: "Bouton" 
                name: "btn" 
                widget: "object" 
                fields:
                  - {label: "Text", name: "title", widget: "string", required: false}
                  - label: "Link"
                    name: "link" 
                    widget: "select" 
                    options:
                      - {label: "Page d'accueil", value: "homePage"}
                      - {label: "Page portfolio", value: "clientsPage"}
                      - {label: "Page services", value: "servicesPage"}
                      - {label: "Page articles", value: "articlesPage"}
                      - {label: "Page contact", value: "contactPage"}
          - {label: "Services - Titre", name: "servicestitle", widget: "string"}
          - {label: "À propos - Gauche", name: "aboutleft", widget: "markdown"}
          - {label: "À propos - Droite", name: "aboutright", widget: "markdown"}
          - {label: "Contact - Entête", name: "contact", widget: "markdown"} 
          - {label: "Texte du bouton", name: "btntext", widget: "string"}  
      - name: "services"
        label: "Services"
        file: "content/services/_index.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Root page", name: "rootPage", widget: "hidden", default: "true"}
          - {label: "Image", name: "image", widget: "image", required: false}
      - name: "formations"
        label: "Formations"
        file: "content/formations/_index.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Texte", name: "body", widget: "markdown", required: false}
      - name: "a-propos"
        label: "À propos"
        file: "content/singles/a-propos.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Lien", name: "slug", widget: "string", default: "ceci-est-un-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Layout", name: "layout", widget: "hidden", default: "a-propos"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Texte", name: "body", widget: "markdown", required: false}
      - name: "equipe"
        label: "Équipe"
        file: "content/singles/equipe.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Lien", name: "slug", widget: "string", default: "ceci-est-un-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Layout", name: "layout", widget: "hidden", default: "equipe"}
          - {label: "Image", name: "image", widget: "image", required: false}
      - name: "liens-utiles"
        label: "Liens utiles"
        file: "content/ressources/liens-utiles.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Lien", name: "slug", widget: "string", default: "ceci-est-un-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Layout", name: "layout", widget: "hidden", default: "liens-utiles"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Texte", name: "body", widget: "markdown", required: false}
      - name: "faq"
        label: "FAQ"
        file: "content/ressources/faq.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Lien", name: "slug", widget: "string", default: "ceci-est-un-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Layout", name: "layout", widget: "hidden", default: "faq"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Texte", name: "body", widget: "markdown", required: false}
      - name: "contact"
        label: "Page contact"
        file: "content/singles/contact.md"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text", required: false}
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Lien", name: "slug", widget: "string", default: "ceci-est-un-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Layout", name: "layout", widget: "hidden", default: "contact"}
          - {label: "Heures d'ouverture", name: "heures", widget: "string"}
          - {label: "Services - Menu déroulant", name: "services", widget: "list"}
          - {label: "Titre du formulaire", name: "sectiontitle", widget: "string"}
          - {label: "Description sous le formulaire", name: "sectiondescription", widget: "text"}
          - {label: "Image", name: "image", widget: "image", required: false}